### PR TITLE
Block category counts for stage

### LINKED ISSUE #28: Block category counts - per stage
Issue #24 broken into smaller tasks.

### PR DESCRIPTION
**Pull request by haietza**
Closes #28.

### CODE REVIEW

File: Submission.java [hunk 1]
```diff
@@ -210,6 +235,195 @@ private int getCountForStage(String item)
...
+        {
+            return;
+        }
+        
+        // If first element is a String, it is the block name.
+        // Get and count its category.
+        if (array.get(0) instanceof String)
+        {
+            String category = getCategory((String) array.get(0));
+            if (category != null)
```
Comment (KaraBeason) [inline Submission.java]: just have a question.. why do you have to typecast array.get(0) to a string if the condition array.get(0) instanceof String evaluates to true?

Comment (haietza) [inline Submission.java]: @KaraBeason The JSONArray and JSON Object stuff are a bit odd - they always return Objects, even though those Objects might actually be other things. So you have to cast them as the type they actually are to get them to behave the proper way. If you look at the example we started with (https://www.mkyong.com/java/json-simple-example-read-and-write-json/) you can see when he is reading the parsed JSON, he has to cast it as well. It won't compile otherwise :(.

File: SubmissionTest.java [hunk 2]
```diff
@@ -603,6 +603,272 @@ public void testGetCostumeCountForSpriteValid()
...
+     */
+    @Test
+    public void testGetControlBlocksForStage()
+    {
+        setUpSubmission(submissions[1]);
+        submissions[1].countBlockCategoriesForStage();
+
+        int expected = 1;
+        int actual = submissions[1].getControlBlocksForStage();
+        assertEquals("should be equal", expected, actual);
```
Comment (KaraBeason) [inline SubmissionTest.java]: Could this be reduced to one line i.e.:
assertEquals("should be equal", 1, submissions[1].getControlBlocksForStage()); 
?

File: Submission.java (hunk 1 above)
Comment (KaraBeason) [inline Submission.java]: Ah, that makes sense.  I forgot it's a JSONArray!  Thanks for explaining :)

File: SubmissionTest.java (hunk 2 above)
Comment (haietza) [inline SubmissionTest.java]: Yes it probably could. But I thought we had been formatting all the unit tests this way? I think it might help for documentation to show that one is our preset expected value and one is the actual value returned from the tested method. BUT - if you think it is clear/documented enough as the one-liner, I can go in and change all of them accordingly. Let me know what you think! Thanks!

Comment (KaraBeason) [inline SubmissionTest.java]: I think you're right!  It does make clear which is the actual and expected parameter without knowledge of the method definition .  A-okay with me!
