### PR TITLE
Fix merge conflicts for expandReport

### LINKED ISSUE #42: Merge Problem
@haietza @KaraBeason Ok so I merged the issue since there were only minor output changes and no code changes since the remove report.txt was already added. I fixed the conflicts in the report.java reportTest.java and the makefile.  I though it was good but after I merged I ran the code and it didn't compile. For some reason the Submission.java file on my branch was different from the master one, but they didn't merge together. This made methods such as  the get costume count for sprite not work since it no longer exist when merged. 
I think it pushed the changes up to master since I fixed the conflicts which is not want I really wanted after finding out it wasn't working. I'm not sure what to do since this is a major problem. Can we revert back? Or should we add the methods in Submission from the one on my branch?

### PR DESCRIPTION
**Pull request by haietza**
Original pull request #31. Closes #42.

### CODE REVIEW

File: Report.java [hunk 1]
```diff
@@ -29,37 +33,116 @@ public Report(Submission[] submissions)
...
-                            System.out.println("Script count: " 
-                                + sprites[i].getScriptCount());
-                            System.out.println();
-                        }
+                        printSpriteCounts(printW, i);
                     }
                 }
             }
+            printW.close();
+
```
Comment (KaraBeason) [inline Report.java]: line 55 can be deleted
